### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_ADClient for XCode 16 build error

### ISSUE THREAD

**Issue by devmucahideyvaz** [myTrackerSDK/mytracker-unity#2]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ADClient", referenced from:
       in MyTrackerSDK[arm64][78](MRIadHandler.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by devmucahideyvaz** [comment]
@altk I can't get build in xcode because of this error.
iAd.framework is deprecated.
I would appreciate it if you could help me.

**Comment by Zaakk** [comment]
SDK has been updated, please try new version
